Getting new error message
root@9acc49a221a7:/home/workspace# ipython bikeshare.py
Hello! Let's explore some US bikeshare data!

Please enter new york city, chicago or washington
washington
Thank you for choosing washington.

Please choose which month (1-6) you would like more information or '0' for all months, ex 1 = January
january
Please retry
Please choose which month (1-6) you would like more information or '0' for all months, ex 1 = January
January
Thank you for your input
Please choose a day (1-7) you would like more information on or "0" for the whole week, ex 1 = Monday
Monday
Thank you for your input
----------------------------------------

Calculating The Most Frequent Times of Travel...

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in na_op(x, y)
    657             result = expressions.evaluate(op, str_rep, x, y,
--> 658                                           raise_on_error=True, **eval_kwargs)
    659         except TypeError:

/opt/conda/lib/python3.6/site-packages/pandas/core/computation/expressions.py in evaluate(op, op_str, a, b, raise_on_error, use_numexpr, **eval_kwargs)
    210         return _evaluate(op, op_str, a, b, raise_on_error=raise_on_error,
--> 211                          **eval_kwargs)
    212     return _evaluate_standard(op, op_str, a, b, raise_on_error=raise_on_error)

/opt/conda/lib/python3.6/site-packages/pandas/core/computation/expressions.py in _evaluate_numexpr(op, op_str, a, b, raise_on_error, truediv, reversed, **eval_kwargs)
    121     if result is None:
--> 122         result = _evaluate_standard(op, op_str, a, b, raise_on_error)
    123

/opt/conda/lib/python3.6/site-packages/pandas/core/computation/expressions.py in _evaluate_standard(op, op_str, a, b, raise_on_error, **eval_kwargs)
     63     with np.errstate(all='ignore'):
---> 64         return op(a, b)
     65

/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in <lambda>(x, y)
     73                          default_axis=default_axis),
---> 74         radd=arith_method(lambda x, y: y + x, names('radd'), op('+'),
     75                           default_axis=default_axis),

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/home/workspace/bikeshare.py in <module>()
    203
    204 if __name__ == "__main__":
--> 205         main()

/home/workspace/bikeshare.py in main()
    192         df = load_data(city, month, day)
    193
--> 194         time_stats(df)
    195         station_stats(df)
    196         trip_duration_stats(df)

/home/workspace/bikeshare.py in time_stats(df)
    102     # TO DO: display the most common month
    103     common_month = df['month'].mode()
--> 104     print("Most common month:" + " "+ common_month + "\n")
    105
    106     # TO DO: display the most common day of week

/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in wrapper(left, right, name, na_op)
    719                 lvalues = lvalues.values
    720
--> 721         result = wrap_results(safe_na_op(lvalues, rvalues))
    722         return construct_result(
    723             left,

/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in safe_na_op(lvalues, rvalues)
    680         try:
    681             with np.errstate(all='ignore'):
--> 682                 return na_op(lvalues, rvalues)
    683         except Exception:
    684             if isinstance(rvalues, ABCSeries):

/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in na_op(x, y)
    666                 result = np.empty(len(x), dtype=x.dtype)
    667                 mask = notnull(x)
--> 668                 result[mask] = op(x[mask], y)
    669             else:
    670                 raise TypeError("{typ} cannot perform the operation "

/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in <lambda>(x, y)
     72         add=arith_method(operator.add, names('add'), op('+'),
     73                          default_axis=default_axis),
---> 74         radd=arith_method(lambda x, y: y + x, names('radd'), op('+'),
     75                           default_axis=default_axis),
     76         sub=arith_method(operator.sub, names('sub'), op('-'),

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')
root@9acc49a221a7:/home/workspace# ipython bikeshare.py
Hello! Let's explore some US bikeshare data!

Please enter new york city, chicago or washington
washington
Thank you for choosing washington.

Please choose which month (1-6) you would like more information or '0' for all months, ex 1 = January
January
Thank you for your input
Please choose a day (1-7) you would like more information on or "0" for the whole week, ex 1 = Monday
Monday
Thank you for your input
----------------------------------------

Calculating The Most Frequent Times of Travel...

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in na_op(x, y)
    657             result = expressions.evaluate(op, str_rep, x, y,
--> 658                                           raise_on_error=True, **eval_kwargs)
    659         except TypeError:

/opt/conda/lib/python3.6/site-packages/pandas/core/computation/expressions.py in evaluate(op, op_str, a, b, raise_on_error, use_numexpr, **eval_kwargs)
    210         return _evaluate(op, op_str, a, b, raise_on_error=raise_on_error,
--> 211                          **eval_kwargs)
    212     return _evaluate_standard(op, op_str, a, b, raise_on_error=raise_on_error)

/opt/conda/lib/python3.6/site-packages/pandas/core/computation/expressions.py in _evaluate_numexpr(op, op_str, a, b, raise_on_error, truediv, reversed, **eval_kwargs)
    121     if result is None:
--> 122         result = _evaluate_standard(op, op_str, a, b, raise_on_error)
    123

/opt/conda/lib/python3.6/site-packages/pandas/core/computation/expressions.py in _evaluate_standard(op, op_str, a, b, raise_on_error, **eval_kwargs)
     63     with np.errstate(all='ignore'):
---> 64         return op(a, b)
     65

/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in <lambda>(x, y)
     73                          default_axis=default_axis),
---> 74         radd=arith_method(lambda x, y: y + x, names('radd'), op('+'),
     75                           default_axis=default_axis),

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
/home/workspace/bikeshare.py in <module>()
    202
    203 if __name__ == "__main__":
--> 204         main()

/home/workspace/bikeshare.py in main()
    191         df = load_data(city, month, day)
    192
--> 193         time_stats(df)
    194         station_stats(df)
    195         trip_duration_stats(df)

/home/workspace/bikeshare.py in time_stats(df)
    101     # TO DO: display the most common month
    102     common_month = df['month'].mode()
--> 103     print("Most common month:" + " "+ common_month + "\n")
    104
    105     # TO DO: display the most common day of week

/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in wrapper(left, right, name, na_op)
    719                 lvalues = lvalues.values
    720
--> 721         result = wrap_results(safe_na_op(lvalues, rvalues))
    722         return construct_result(
    723             left,

/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in safe_na_op(lvalues, rvalues)
    680         try:
    681             with np.errstate(all='ignore'):
--> 682                 return na_op(lvalues, rvalues)
    683         except Exception:
    684             if isinstance(rvalues, ABCSeries):

/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in na_op(x, y)
    666                 result = np.empty(len(x), dtype=x.dtype)
    667                 mask = notnull(x)
--> 668                 result[mask] = op(x[mask], y)
    669             else:
    670                 raise TypeError("{typ} cannot perform the operation "

/opt/conda/lib/python3.6/site-packages/pandas/core/ops.py in <lambda>(x, y)
     72         add=arith_method(operator.add, names('add'), op('+'),
     73                          default_axis=default_axis),
---> 74         radd=arith_method(lambda x, y: y + x, names('radd'), op('+'),
     75                           default_axis=default_axis),
     76         sub=arith_method(operator.sub, names('sub'), op('-'),

TypeError: ufunc 'add' did not contain a loop with signature matching types dtype('<U21') dtype('<U21') dtype('<U21')